---
- name: Basic usage
  ansible.builtin.debug:
    msg:
      - "'AZURE_CLIENT_ID {{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}'"
      - "'AZURE_SUBSCRIPTION_ID {{ lookup('ansible.builtin.env', 'AZURE_SUBSCRIPTION_ID') }}'"
      - "'AZURE_TENANT {{ lookup('ansible.builtin.env', 'AZURE_TENANT') }}'"

- name: Get list of all regions
  azure.azcollection.azure_rm_resource_info:
    url: "/locations"
    api_version: "2020-01-01"
  register: all_regions

- name: print var
  debug:
    msg: "{{ all_regions }}"

- name: get all networks
  azure.azcollection.azure_rm_virtualnetwork_info:
  register: azure_networks

- name: print azure_networks
  ansible.builtin.debug:
    msg: "{{ azure_networks }}"

- name: get all vms
  azure.azcollection.azure_rm_virtualmachine_info:
  register: azure_vms

- name: print azure_vms
  ansible.builtin.debug:
    msg: "{{ azure_vms }}"

- name: Get facts for network interfaces
  azure_rm_networkinterface_info:
  register: network_interfaces

- name: print azure_vms
  ansible.builtin.debug:
    msg: "{{ network_interfaces }}"