---
- name: Application deployment Playbook
  hosts: localhost
  gather_facts: false
  become: true
  
  tasks:
    - name: Make sure application is not empty
      ansible.builtin.assert:
        that:
          - "application != '' "

    - name: Print to terminal the application to be installed
      ansible.builtin.debug:
        msg: "This Ansible Playbook will install {{application}}"

    - name: Install the application(s)
      ansible.builtin.dnf:
        name: "{{application}}"
        allow_downgrade: true
      register: result

    - name: Print to terminal the applications that have been installed
      ansible.builtin.debug:
        msg: "The application: {{application}} has been installed"
      when: result.changed|bool

    - name: Print to terminal the applications that are already previously installed
      ansible.builtin.debug:
        msg: "The application: {{application}} was already installed"
      when: not result.changed|bool
